name: Call a reusable workflow

on:
  push:
    branches:
      - main

jobs:
  call-workflow-passing-data:
    permissions:
      contents: read
      pull-requests: write
    uses: SandBoxFeatureOrg/required-workflow-sandbox/.github/workflows/called-workflow.yml@main
    with:
      var_a: ${{ vars.VAR_A }}
      var_b: ${{ vars.VAR_B }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
